### PR TITLE
Fix collections.abc import for Python 3.9

### PR DESCRIPTION
**Pull request by hugovk**
The Python 3.9 build is failing:

```
geopy/point.py:264: in __eq__
    if not isinstance(other, collections.Iterable):
E   AttributeError: module 'collections' has no attribute 'Iterable'
```

https://travis-ci.org/geopy/geopy/jobs/645182137#L297

Python 3.8 warns about the removal:

```
  /home/travis/build/geopy/geopy/geopy/point.py:264: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
```

https://travis-ci.org/geopy/geopy/jobs/645182134#L306

This change fixes the 3.9 build.

### CODE REVIEW

**Comment by hugovk** [comment]
The PyPy3 failure is an unrelated timeout.

It passed on my fork: https://travis-ci.com/hugovk/geopy/jobs/283044372

**Comment by KostyaEsmukov** [comment]
I'm sorry but I will have to close this, because geopy 1.x will not support Python 3.9, but geopy 2.0 branch already contains this fix, see #335

**Comment by hugovk** [comment]
OK! How about removing the failing 3.9 testing from the 1.x/master branch?

**Comment by KostyaEsmukov** [comment]
Thanks for understanding!

> How about removing the failing 3.9 testing from the 1.x/master branch?

Would that solve any problem? :) 

I think it's good to have it here to keep reminded that 1.x branch doesn't work with 3.9

**Comment by hugovk** [comment]
It'd save some resources, free up some slots on the CI, save some electricity.

Seeing the failing build also suggests you do want eventually it to work with 3.9, but it's not yet ready, hence this PR :)
